console.log("hello I am telling you something about me")
console.log("I am Krishna Singh i am fourtheen years old")
console.log("I studing in class-8th,in section D")
console.log("my school name is Wendy Scholl Junior Collage")
console.log("My Hobi is descover new things and I like to do crafting")
console.log("My father name is Yogesh Singh")
console.log("My mother name is Sonali Singh")